---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.kubernetes

  tasks:
    - name: Login to OCP
      command: oc login $OCP_SERVER -u $OCP_USERNAME -p $OCP_PASSWORD --insecure-skip-tls-verify

    - set_fact:
        custom_resources:
        - TsscPlatform

    - name: Remove CR
      k8s:
        api_version: v1alpha1
        kind: '{{ item }}'
        state: absent
        name: '{{ item | lower }}-testing'
        namespace: '{{ namespace }}'
      ignore_errors: true
      loop: '{{ custom_resources }}'

    - name: Wait for CR to be deleted
      k8s_info:
        api_version: v1alpha1
        kind: '{{ item }}'
        name: '{{ item | lower }}-testing'
        namespace: '{{ namespace }}'
      register: result
      until: result.resources | length == 0
      ignore_errors: true
      retries: 30
      delay: 10
      loop: '{{ custom_resources }}'

    - name: Remove Namespaces
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
        state: absent
      loop: '{{ custom_resources }}'
