---
## Create Realm and Configure Openshift IDP
- name: Check for ConfigMap with CA bundle
  k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: openshift-config
    name: ca-config-map
  register: configmap_present
  when:
  - not trusted_router_certificates|bool
  - cr_state == 'present'

- name: Fail if the configmap isn't present and it should be
  fail:
    msg: >
      Before you can create the RH-SSO Identity Provider for OpenShift,
      you must upload the CA that signs your publicly-accessible certificates
      for cluster services (specifically, the console) for redirects to work.
      Please name the bundle `ca-config-map` in the `openshift-config` Project.
  when:
  - not trusted_router_certificates|bool
  - configmap_present.resources|length < 1
  - cr_state == 'present'

- name: 'Set Realm state to {{ cr_state }}'
  k8s:
    definition: '{{ lookup("template", "rhsso-ocp-realm.yml.j2")|from_yaml }}'
    state: '{{ cr_state }}'

- name: 'Set OCP SSO Client state to {{ cr_state }}'
  k8s:
    definition: '{{ lookup("template", "rhsso-ocp-client.yml.j2")|from_yaml }}'
    state: '{{ cr_state }}'

- name: Create RH-SSO IdP in OpenShift
  k8s_json_patch:
    api_version: config.openshift.io/v1
    kind: OAuth
    name: cluster
    patch:
    - op: add
      path: /spec/identityProviders/[?name='{{ item.name }}']
      value: '{{ item }}'
  loop: '{{ lookup("template", "rhsso-ocp-idp.yml.j2")|from_yaml }}'
