---
dist: bionic
language: python
services:
- docker
install:
- mkdir -p $HOME/.local/bin
- export PATH="$HOME/.local/bin:$PATH"
- pip3 install docker==4.2.2 molecule==3.1.5 ansible-lint yamllint flake8 openshift jmespath
- ansible-galaxy collection install -r requirements.yml
- curl -Lo $HOME/oc.tar.gz http://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
- tar xvzf $HOME/oc.tar.gz -C $HOME/.local/bin oc
- curl -Lo $HOME/helm.tgz https://get.helm.sh/helm-v3.3.0-linux-amd64.tar.gz
- tar xvzf $HOME/helm.tgz -C $HOME/.local/bin --strip-components 1 linux-amd64/helm
sudo: true
before_script:
- sudo sysctl -w vm.max_map_count=262144
script:
- make kustomize
- '[ -f ./bin/kustomize ] && export KUSTOMIZE="$(realpath ./bin/kustomize)" || export KUSTOMIZE="$(which kustomize)"'
- molecule test -s ocp-cluster
deploy:
- provider: script
  script: hack/operate.sh --push-images --bundle --develop --verbose --formatter
  on:
    branch: develop
- provider: script
  script: hack/operate.sh --push-images --bundle --extra-tag=latest --verbose --formatter
  on:
    branch: main
