---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create test kind cluster
    command: kind create cluster --name osdk-test --config=files/kind-config.yml --kubeconfig {{ kubeconfig }}

  - name: Install nginx Ingress onto kind
    command: helm install kind-ingress stable/nginx-ingress --set controller.service.type=NodePort --set controller.service.nodePorts.http=30080
